#
# Copyright (c) Microsoft Corporation
# Licensed under the MIT License.
#
name: CAF L0-2 Credentials Public Access (by blinQ)

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [labeled]

concurrency:
  group: CAF-L0

env:
  LZ_REPO: '{{ ignite.global.lz_repo }}'
  LZ_REF: '{{ ignite.global.lz_ref }}'
  CAF_REPO: '{{ ignite.global.caf_repo }}'
  CAF_REF: '{{ ignite.global.caf_ref }}'
  CAF_ENVIRONMENT: {{ ignite.global.caf_environment }}

permissions:
    id-token: write
    contents: read
{% raw %}
jobs:
  environment:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'CAF-L0-CREDENTIALS') || github.event.schedule != '' || github.event_name == 'workflow_dispatch' }}
    name: Setup Environment
{% endraw %}
    runs-on: [self-hosted, rover-{{ ignite.global.caf_environment }}]
{% raw %}
    outputs:
      lz_repo: ${{ steps.set_env.outputs.lz_repo }}
      lz_ref: ${{ steps.set_env.outputs.lz_ref }}
      caf_repo: ${{ steps.set_env.outputs.caf_repo }}
      caf_ref: ${{ steps.set_env.outputs.caf_ref }}
      environment: ${{ steps.set_env.outputs.environment }}
    steps:
      - name: Set environment variables for reusable workflows
        id: set_env
        run: |
          echo "lz_repo=$LZ_REPO" >> $GITHUB_OUTPUT
          echo "lz_ref=$LZ_REF" >> $GITHUB_OUTPUT
          echo "caf_repo=$CAF_REPO" >> $GITHUB_OUTPUT
          echo "caf_ref=$CAF_REF" >> $GITHUB_OUTPUT
          echo "environment=$CAF_ENVIRONMENT" >> $GITHUB_OUTPUT

  credentials:
    name: Credentials
    uses: blinqas/azlz-workflows/.github/workflows/rover-by-blinq.yaml@main
    needs: [environment]
    permissions:
      id-token: write
      contents: read
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_LAUNCHPAD_SUBSCRIPTION_ID: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
      AZURE_TARGET_SUBSCRIPTION_ID: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
    with:
      jobs: "plan, apply"
      lz_ref: ${{ needs.environment.outputs.lz_ref }}
      lz_repo: ${{ needs.environment.outputs.lz_repo }}
      caf_ref: ${{ needs.environment.outputs.caf_ref }}
      caf_repo: ${{ needs.environment.outputs.caf_repo }}
      environment: ${{ needs.environment.outputs.environment }}
      caf_identity_aad_key: cred_identity
      landingzone_code_path: ./landingzones/caf_solution
      landingzone_configuration_path: ./platform/configuration/level0/credentials_public
      plan_path: ${GITHUB_WORKSPACE}/launchpad_credentials.tfstate.tfplan
      tfstate: launchpad_credentials.tfstate
      level: level0
      terraform_action: plan_apply
{% endraw %}