- name: Output regions
  debug:
    msg: "Regions = {{ regions }}"

- name: Azure Regions
  set_fact:
    azure_regions: "{{ regions | from_json | default({'region1': 'westeurope', 'region2': 'norwayeast'})}}"

- name: Azure Regions List
  set_fact:
    azure_regions_list: "{{ azure_regions.values() | list }}"

- name: Default email addresses
  set_fact:
    security_email_address: "{{ security_email_address | default('support@blinq.no') }}"
    noc_email_address: "{{ noc_email_address | default('support@blinq.no') }}"

